package parser;

/* Generated By:JJTree: Do not edit this line. ASTconstraints.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTconstraints extends SimpleNode {
  public ASTconstraints(int id) {
    super(id);
  }

  public ASTconstraints(Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=fa48f9efcf675afd4c8e879d4f6a5054 (do not edit this line) */
