package parser;

/* Generated By:JJTree: Do not edit this line. ASTdomain.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTdomain extends SimpleNode {
  public ASTdomain(int id) {
    super(id);
  }

  public ASTdomain(Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=248ff2397a823b7b86cea53392afcca3 (do not edit this line) */
