package parser;

/* Generated By:JJTree: Do not edit this line. ASTgeq.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTgeq extends SimpleNode {
  public ASTgeq(int id) {
    super(id);
  }

  public ASTgeq(Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=8956f7329c880086c43970828f74400a (do not edit this line) */
