package parser;

/* Generated By:JJTree: Do not edit this line. ASTg.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTg extends SimpleNode {
  public ASTg(int id) {
    super(id);
  }

  public ASTg(Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=7ba8a4faf4c69bb73d9d35fbd3b2a057 (do not edit this line) */
