package parser;

/* Generated By:JJTree: Do not edit this line. ASTgeq.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTgeq extends SimpleNode {
  public ASTgeq(int id) {
    super(id);
  }

  public ASTgeq(Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=d96f13463d2e99dc6cc9fdb00107b57a (do not edit this line) */
