package parser;

/* Generated By:JJTree: Do not edit this line. ASTinteger.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTinteger extends SimpleNode {
  public ASTinteger(int id) {
    super(id);
  }

  public ASTinteger(Parser p, int id) {
    super(p, id);
  }

  public int value = -666;

  public String toString()
  {
    return super.toString() + " {" + value + "}";
  }

  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=5696218af838e61f020c8cc4a4d71b60 (do not edit this line) */
