package parser;

/* Generated By:JJTree: Do not edit this line. ASTinteger.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTinteger extends SimpleNode {
  
  public int value = 0;
  
  public ASTinteger(int id) {
    super(id);
  }

  public ASTinteger(Parser p, int id) {
    super(p, id);
  }
  
  
  public void setValue(String v) throws NumberFormatException {
	try {
		value = Integer.parseInt(v);
	}
	catch (NumberFormatException e) {
		throw new NumberFormatException("[Parser] " + v + " is not a valid Integer.");
	}
  }
  
  public int getValue() {
    return value;
  }
  public String toString() {
    return (new Integer(value)).toString();
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=9d828042e2f0311cfdef6ccc374e4923 (do not edit this line) */
