package parser;

/* Generated By:JJTree: Do not edit this line. ASTl.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTl extends SimpleNode {
  public ASTl(int id) {
    super(id);
  }

  public ASTl(Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=0a2ae8701e8f431825f9a39d6adc9971 (do not edit this line) */
