package parser;

/* Generated By:JJTree: Do not edit this line. ASTleq.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTleq extends SimpleNode {
  public ASTleq(int id) {
    super(id);
  }

  public ASTleq(Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=bb7e05fa78212965f823b69403eb4815 (do not edit this line) */
