package parser;


/* Generated By:JJTree: Do not edit this line. ASTmul.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTmul extends SimpleNode {
  public ASTmul(int id) {
    super(id);
  }

  public ASTmul(Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=a8a80218fdf1926b51a2b428bfbd0e80 (do not edit this line) */
