package parser;

/* Generated By:JJTree: Do not edit this line. ASTminus.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTminus extends SimpleNode {
  public ASTminus(int id) {
    super(id);
  }

  public ASTminus(Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=ff726ed612e5cf35b532383ad7706398 (do not edit this line) */
