package parser;

/* Generated By:JJTree: Do not edit this line. ASTneq.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTneq extends SimpleNode {
  public ASTneq(int id) {
    super(id);
  }

  public ASTneq(Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=247474c1cdc7199d3cfaf489f3a2101b (do not edit this line) */
