package parser;

/* Generated By:JavaCC: Do not edit this line. ParserTreeConstants.java Version 4.2 */
public interface ParserTreeConstants
{
  public int JJTCONSTRAINTS = 0;
  public int JJTDOMAIN = 1;
  public int JJTVAR = 2;
  public int JJTINTEGER = 3;
  public int JJTCONSTRAINT = 4;
  public int JJTEQ = 5;
  public int JJTNEQ = 6;
  public int JJTLEQ = 7;
  public int JJTGEQ = 8;
  public int JJTG = 9;
  public int JJTL = 10;
  public int JJTVOID = 11;
  public int JJTMUL = 12;
  public int JJTDIV = 13;
  public int JJTPLUS = 14;
  public int JJTMINUS = 15;


  public String[] jjtNodeName = {
    "constraints",
    "domain",
    "var",
    "integer",
    "constraint",
    "eq",
    "neq",
    "leq",
    "geq",
    "g",
    "l",
    "void",
    "mul",
    "div",
    "plus",
    "minus",
  };
}
/* JavaCC - OriginalChecksum=c80ba93a89547dbe577c932c8db47607 (do not edit this line) */
