package parser;

/* Generated By:JJTree&JavaCC: Do not edit this line. ParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int IDENTIFIER = 5;
  /** RegularExpression Id. */
  int INTEGER = 6;
  /** RegularExpression Id. */
  int DIGIT = 7;
  /** RegularExpression Id. */
  int LETTER = 8;
  /** RegularExpression Id. */
  int SPECIALSYMB = 9;
  /** RegularExpression Id. */
  int LB = 10;
  /** RegularExpression Id. */
  int RB = 11;
  /** RegularExpression Id. */
  int LP = 12;
  /** RegularExpression Id. */
  int RP = 13;
  /** RegularExpression Id. */
  int BOUNDS = 14;
  /** RegularExpression Id. */
  int COMMA = 15;
  /** RegularExpression Id. */
  int SEMICOLON = 16;
  /** RegularExpression Id. */
  int DOMAIN_DEF = 17;
  /** RegularExpression Id. */
  int PLUS = 18;
  /** RegularExpression Id. */
  int MINUS = 19;
  /** RegularExpression Id. */
  int TIMES = 20;
  /** RegularExpression Id. */
  int DIV = 21;
  /** RegularExpression Id. */
  int NEQ = 22;
  /** RegularExpression Id. */
  int EQ = 23;
  /** RegularExpression Id. */
  int LEQ = 24;
  /** RegularExpression Id. */
  int GEQ = 25;
  /** RegularExpression Id. */
  int G = 26;
  /** RegularExpression Id. */
  int L = 27;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "<IDENTIFIER>",
    "<INTEGER>",
    "<DIGIT>",
    "<LETTER>",
    "<SPECIALSYMB>",
    "\"[\"",
    "\"]\"",
    "\"(\"",
    "\")\"",
    "\",...,\"",
    "\",\"",
    "\";\"",
    "\"*:\"",
    "\"*+\"",
    "\"*-\"",
    "\"***\"",
    "\"*/\"",
    "\"*/=\"",
    "\"*=\"",
    "\"*=<\"",
    "\"*>=\"",
    "\"*>\"",
    "\"*<\"",
  };

}
